### PR TITLE
Reorganized directory structure 

### PR DESCRIPTION
**Pull request by jesings**
Reorganized directory structure into src/, tests/, lind/, and docs/, added script frontend to build process, and removed extraneous files.

### CODE REVIEW

**Comment by rennergade** [comment]
It's complaining about a conflict above, please fix. Also as noted, remove the pipe related commit from this PR. 

Otherwise, looks great. Will merge when ready!

**Comment by jesings** [comment]
I don't necessarily see a problem with the pipe commit, because we are pulling to develop rather than master, but if you'd like me to remove that commit, that would be fine.

**Comment by rennergade** [comment]
My plan is to merge these changes into develop, and then merge develop into master. So I'd love to keep the pipe stuff out of here for now. Thanks!

**Comment by JustinCappos** [comment]
I agree with @rennergade here.  It's really important to have PRs and commits only contain one thing.  It may seem like a silly thing now, but 3 years from now when you're trying to sort out what a set of changes did, it will save a ton of time and headache.  It also will make debugging easier in the meantime in case one or the other breaks something we can easily know what change it was.

**Comment by jesings** [comment]
I completed a rebase to remove the commit for pipe syscalls.

**Pull request merged**
